version: '3.8'

services:
  postgres-master-library:
    image: postgres:14.5
    environment:
      POSTGRES_POSTGRES_PASSWORD: ivanov_214
      POSTGRES_USERNAME: ivanov_214
      POSTGRES_PASSWORD: ivanov_214
      POSTGRES_DATABASE: ivanov_214
      REPMGR_PASSWORD: ivanov_214
    ports:
      - "5432:5432"
    volumes:
      - .\docker\db\scripts\library.sql:/docker-entrypoint-initdb.d/library.sql

  postgres-master-trains:
    image: postgres:14.5
    environment:
      POSTGRES_POSTGRES_PASSWORD: ivanov_214
      POSTGRES_USERNAME: ivanov_214
      POSTGRES_PASSWORD: ivanov_214
      POSTGRES_DATABASE: ivanov_214
      REPMGR_PASSWORD: ivanov_214
    ports:
      - "5434:5432"
    volumes:
      - .\docker\db\scripts\trains.sql:/docker-entrypoint-initdb.d/trains.sql

  postgres-master-hospital:
    image: postgres:14.5
    environment:
      POSTGRES_POSTGRES_PASSWORD: ivanov_214
      POSTGRES_USERNAME: ivanov_214
      POSTGRES_PASSWORD: ivanov_214
      POSTGRES_DATABASE: ivanov_214
    ports:
      - "5436:5432"
    volumes:
      - .\docker\db\scripts\hospital.sql:/docker-entrypoint-initdb.d/hospital.sql